name: Generate Badge

on: 
  workflow_dispatch:

jobs:
  generate_badge:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' 

      - name: Install dependencies
        run: |
          pip install requests

      - name: Generate unique badge
        run: python .github/workflows/generate_badge.py
        env:
          ENV_SECRET: ${{ secrets.HF_TOKEN }} 

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update badge"
          file_pattern: badges/* README.md
